# Generated by Django 5.2.6 on 2025-10-06 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_locked_until_user_failed_login_attempts_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=512)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('flagged_as_suspicious', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('new_device_login', 'New Device Login'), ('account_locked', 'Account Locked'), ('account_recovery', 'Account Recovery Attempted'), ('suspicious_login', 'Suspicious Login Attempt')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4/IPv6', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login_ip'], name='users_last_lo_e6f76e_idx'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-timestamp'], name='login_histo_user_id_9c165b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['flagged_as_suspicious'], name='login_histo_flagged_0a21a1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', '-timestamp'], name='security_ev_user_id_697e95_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type'], name='security_ev_event_t_77edde_idx'),
        ),
    ]
