# Generated by Django 5.2.6 on 2025-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginhistory_securityevent_user_last_login_ip_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bankid_personal_number',
            field=models.CharField(blank=True, help_text='Hashed Swedish personnummer (never store raw)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bankid_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bankid_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['bankid_personal_number'], name='users_bankid__c54fe2_idx'),
        ),
    ]
